### ISSUE TITLE
Separating build and test in the circle ci config

### ISSUE THREAD

**Issue by a5rar** [ministryofjustice/laa-apply-for-legal-aid#10]
Currently the build and test run in the same job.  It is a good idea to separate these into two jobs so we can rerun from a failed point easily without having to rerun the tests.

```
test:
    <<: *container_config
    steps:
      - checkout
      - *setup_python_env
      - run: python3 manage.py test

  build:
    <<: *container_config
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - *build_docker_image
- *push_docker_image```

**Comment by colinbruce** [comment]
There are now definitely multiple steps so this can probably be closed/ replaced with new issues about exciting new enhancements we can make! Merry 🎄
