### ISSUE TITLE
Failure to upgrade sidekiq to version 6

### ISSUE THREAD

**Issue by Obsiye** [ministryofjustice/laa-apply-for-legal-aid#1469]
During the upgrade to Rails 6 we defaulted sidekiq to version 5.7.2 because version 6 requires zeitwerk (the Rails 6 default autoloader) which we don't use.

more information here:
https://github.com/ministryofjustice/laa-apply-for-legal-aid/pull/1240

**Comment by mpw5** [comment]
Sidekiq is currently at 6.1.2 and appears to be working fine with both Zeitwerk and Classic autoloaders. Closing this issue.
