### ISSUE TITLE
Refactor Applications create action

### ISSUE THREAD

**Issue by lostie** [ministryofjustice/laa-apply-for-legal-aid#20]
Relates to: https://github.com/ministryofjustice/laa-apply-for-legalaid-api/pull/19

* The controller action is doing to much and the logic implemented in it should probably be extracted to a service object
* The specs need tyding up as there's local variables being declared out of the scope of the `it` block, expectations on `not` being nil when we know exactly the value the attribute should have instead. etc

**Comment by heidar** [comment]
I think this one can be closed now, what do you think @lostie?
