### ISSUE TITLE
Mailer tests in the request tests were removed on Rails 6 upgrade

### ISSUE THREAD

**Issue by Obsiye** [ministryofjustice/laa-apply-for-legal-aid#2019]
Remove mailer tests in the request tests. This is because sidekiq is overridden in request tests by the test adapter (in Rails 6) and thus sidekiq mailer tests in the requests were faulting "rails/rails #37270" and the solution is to continue using the test adapter as the mailers are tested seperately.

[Rails 6 upgrade PR](https://github.com/ministryofjustice/laa-apply-for-legal-aid/pull/1240)

**Comment by Obsiye** [comment]
This is less of an issue but something to watch for when it's fixed so that we can then reverse that change. It'll make the request tests singing emails testing a little bit more robust as the mailers are already tested in mailer tests.

**Comment by mpw5** [comment]
Email functionality was refactored in [AP-2011](https://github.com/ministryofjustice/laa-apply-for-legal-aid/pull/2302) and test re-written then, so I'll close this issue as it's no longer relevant.
