### ISSUE TITLE
"Sidekiq alive" incompatible with Sidekiq 6

### ISSUE THREAD

**Issue by scruti** [ministryofjustice/laa-apply-for-legal-aid#817]
Recently, after an [automated bump to Sidekiq 6 from Sidekiq 5.2,](https://github.com/ministryofjustice/laa-apply-for-legal-aid/pull/798) workers started raising errors in kubernetes:
```
uninitialized constant Sidekiq::Logging
Did you mean?  Logger
/usr/local/bundle/gems/sidekiq_alive-1.1.0/lib/sidekiq_alive.rb:78:in `logger'
/usr/local/bundle/gems/sidekiq_alive-1.1.0/lib/sidekiq_alive.rb:14:in `block (3 levels) in start'
/usr/local/bundle/gems/sidekiq_alive-1.1.0/lib/sidekiq_alive.rb:13:in `tap'
/usr/local/bundle/gems/sidekiq_alive-1.1.0/lib/sidekiq_alive.rb:13:in `block (2 levels) in start'
/usr/local/bundle/gems/sidekiq-6.0.0/lib/sidekiq/util.rb:61:in `block in fire_event'
/usr/local/bundle/gems/sidekiq-6.0.0/lib/sidekiq/util.rb:60:in `each'
/usr/local/bundle/gems/sidekiq-6.0.0/lib/sidekiq/util.rb:60:in `fire_event'
/usr/local/bundle/gems/sidekiq-6.0.0/lib/sidekiq/cli.rb:75:in `run'
/usr/local/bundle/gems/sidekiq-6.0.0/bin/sidekiq:12:in `<top (required)>'
/usr/local/bundle/bin/sidekiq:23:in `load'
```

By the log and some investigation seems the error es triggered by the Gem "Sidekiq Alive" that has a [hard dependency on "Sidekiq::Logging"](https://github.com/arturictus/sidekiq_alive/blob/3c00f7d4529976d17776c773fd015f82f18dce8d/lib/sidekiq_alive.rb#L78). I guess Sidekiq 6 stopped exposing it, hence "Sidekiq Alive" blows up.

Sidekiq alive doesn't seem very active, has no newer version adding compatibility to Sidekiq 6 neither raised issues on the error. 

Going to raise an issue in "Sidekiq alive" project, but until a new version is released we won't be able to upgrade to Sidekiq v6.

**Comment by mpw5** [comment]
`Dependabot` opened another PR to bump `sidekiq`today. I've closed the PR and set `dependabot` to not open any more for this dependency (for now) to prevent any accidental updates before this issue is resolved.

**Comment by mpw5** [comment]
`sidekiq_alive` was fixed at some point in the past and we have subsequently succesfully bumped to the latest version. Closing the issue.
