### ISSUE TITLE
Unit testing for JS functionality

### ISSUE THREAD

**Issue by lostie** [ministryofjustice/laa-apply-for-legal-aid#83]
If there's a bit chunk of functionality developed in Javascript it should probably have some Unit tests in place to cover more thoroughly the different scenarios that functionality provides.

Not to be taken as the way to go, but more of an idea/guideline, here's some example of what was done in other projects to achieve the same purpose: https://github.com/ministryofjustice/Claim-for-Crown-Court-Defence/blob/master/spec/javascripts/Modules.OffenceSearchInput_spec.js

**Comment by mpw5** [comment]
We've had `jest` tests for javascript for some time now. Closing this issue.
