### ISSUE TITLE
Background job for True Layer data pull

### ISSUE THREAD

**Issue by lostie** [ministryofjustice/laa-apply-for-legal-aid#98]
Currently the user experience of authenticating in True Layer (and pulling the data) happens all sequentially and gives the user the feeling that they're waiting for something on the True Layer screen where at that point we successfully authenticated them and we're just pulling the information associated with their account, which takes a while.

I suggest the process is enqueued into a Background job manager (like Sidekiq) and the user sees a waiting screen (controlled by us) that is shown stating the data is being pulled down and once the data pull is complete then the user is redirected to the details screen. (Probably better to check with Product and Desing on how the workflow should behave and look).

This should also free up the actual Rails instance, allocated at the given time to the data pull, which avoids cases such as having multiple people performing pulls and blocking/degrading the experience of the app.

**Comment by Kalagan** [comment]
Fixed by https://github.com/ministryofjustice/laa-apply-for-legal-aid/pull/212
